kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cuda
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: driver
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: kernel
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cuda-repo
  namespace: nvidia-gpu-operator
data:
  cuda.repo-x86_64: |
    [cuda]
    name=cuda
    baseurl=https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64
    enabled=1
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA
binaryData: {}
immutable: false
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kernel
  namespace: nvidia-gpu-operator
immutable: false
data:
  kernel.sh: |-
    #!/bin/bash

    dnf install -y jq dnf-plugins-core;
    #This fails, lets try to skip it as it seems to be already enabled
    dnf config-manager --set-enabled crb;
    mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS};
    cd ~/rpmbuild/SOURCES;

    CENTOS_STREAM_9_REPO_ID="24152864"
    CENTOS_STREAM_9_RPM_BRANCH_NAME="c9s"

    CENTOS_STREAM_10_REPO_ID="56169485"
    CENTOS_STREAM_10_RPM_BRANCH_NAME="c10s"

    CENTOS_REPO_ID="${CENTOS_STREAM_10_REPO_ID}"
    RPM_BRANCH_NAME="${CENTOS_STREAM_10_RPM_BRANCH_NAME}"
    # We search kernel sources by tag name and download its tarball. And we search
    # the 500 most recent commits in order to find our kernel versions source rpm files.
    # For Gitlab API documentation see:
    #
    # https://docs.gitlab.com/api/commits/
    # https://docs.gitlab.com/api/rest/#pagination
    # https://docs.gitlab.com/api/tags/
    # https://docs.gitlab.com/api/repositories/#get-file-archive
    #
    # Kernel sources can be found in https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9
    # SRPM sources can be found in https://gitlab.com/redhat/centos-stream/rpms/kernel
    export KVer="$(uname -r)";
    kernel_source_commit=$(curl -L "https://gitlab.com/api/v4/projects/${CENTOS_REPO_ID}/repository/tags?search=${KVer%.x86_64}" 2>/dev/null | jq --raw-output -e '.[] | .target');
    echo "kernel_source_commit ${kernel_source_commit}"
    # We need to repack the archive as the foldername does not match our expectations...
    curl -L "http://gitlab.com/api/v4/projects/${CENTOS_REPO_ID}/repository/archive.tar.gz?sha=${kernel_source_commit}" 2>/dev/null | tar xzf -; mv centos* linux-${KVer%.x86_64}; tar -cf - linux-${KVer%.x86_64}/ | xz -0 -T0 - > linux-${KVer%.x86_64}.tar.xz;

    for p in {1..5}; do
      rpm_source_commit=$(curl -L "https://gitlab.com/api/v4/projects/23664863/repository/commits?ref_name=${RPM_BRANCH_NAME}&path%2Fkernel%2Fkernel.spec&per_page=100&page=${p}" 2>/dev/null | jq --raw-output -e '.[] | select(.title=="kernel-'${KVer%.x86_64}'") | .id') ;
      if [ $? -eq 0 ]; then
        unset KVer;
        # As we found our commit we can fetch it, in order to only fetch what we need
        # we do it by hand as described in
        # https://thelinuxcode.com/clone-git-repository-with-specific-revisions-changeset/;
        git init .;
        git remote add origin https://gitlab.com/redhat/centos-stream/rpms/kernel.git;
        git fetch --depth 1 origin ${rpm_source_commit};
        git checkout ${rpm_source_commit};
        mv kernel.spec ../SPECS/;
        unset rpm_source_commit;
        unset kernel_source_commit;
        break;
      fi;
    done;
    cd ~/rpmbuild/ ;
    dnf builddep -y SPECS/kernel.spec;
    rpmbuild -bb --with baseonly --without pae --without debug --without zfcpdump --without arm64_64k --without realtime  --without realtime_arm64_64k --without cross_headers --without perf --without tools --without debuginfo --with kernel_abi_stablelists --without selftests --clean --target x86_64 SPECS/kernel.spec;
    rm -rf ~/rpmbuild/BUILD;
    rm -rf ~/rpmbuild/BUILDROOT;
    rm -rf ~/rpmbuild/SOURCES;
    dnf clean all;
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cuda
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'cuda:13.0-base-centos10'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'driver-toolkit:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi10/ubi:latest

      ENV PKG_CMD=dnf

      ENV NVARCH=x86_64
      ENV NVIDIA_REQUIRE_CUDA="cuda>=13.0 brand=unknown,driver>=580,driver<581"

      COPY cuda.repo-x86_64 /etc/yum.repos.d/cuda.repo

      LABEL maintainer="NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>"

      RUN NVIDIA_GPGKEY_SUM=afbea87d3b979b3788ef34223aeeb323ade481128e2c133723ae99b8a51368bb && \
          curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/rhel10/${NVARCH}/CDF6BA43.pub | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA && \
          echo "$NVIDIA_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA" | sha256sum -c --strict -

      ENV CUDA_VERSION=13.0.2

      RUN ${PKG_CMD} install -y \
          cuda-cudart-13-0 \
          cuda-compat-13-0 \
          && ${PKG_CMD} clean all \
          && rm -rf /var/cache/yum/*

      # nvidia-docker 1.0
      RUN echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/nvidia.conf

      ENV PATH=/usr/local/cuda/bin:${PATH}
      ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64

      ADD https://gitlab.com/nvidia/container-images/cuda/-/raw/master/NGC-DL-CONTAINER-LICENSE /NGC-DL-CONTAINER-LICENSE

      # nvidia-container-runtime
      ENV NVIDIA_VISIBLE_DEVICES=all
      ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
    configMaps:
      - configMap:
          name: cuda-repo
        destinationDir: .
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: driver-pb
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'driver:580-6.12.0-142.el10.x86_64-scos10'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: DRIVER_TOOLKIT_IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/openshift/driver-toolkit:10.0.20251023-0'
        - name: CUDA_DIST
          value: centos10
        - name: KERNEL_VERSION
          value: 6.12.0-142.el10.x86_64
        - name: KERNEL_VERSION_NOARCH
          value: 6.12.0-142.el10
        - name: RHEL_VERSION
          value: 10.0.20251023-0
        - name: RHEL_VERSION_MAJOR
          value: '10'
        - name: BUILD_ARCH
          value: x86_64
        - name: TARGET_ARCH
          value: x86_64
        - name: DRIVER_VERSION
          value: 580.105.08
        - name: DRIVER_EPOCH
          value: '1'
        - name: BUILDER_USER
          value: Jean-Gabriel Gill-Couture
        - name: BUILDER_EMAIL
          value: jg@nationtech.io
        - name: DRIVER_STREAM_TYPE
          value: stable
        - name: CUDA_VERSION
          value: 13.0.2
  postCommit: {}
  source:
    type: Git
    dockerfile: |
      # This dockerfile is adapted from https://github.com/NVIDIA/gpu-driver-container/blob/main/rhel10/precompiled/Dockerfile
      # ... (comments remain the same)

      ARG DRIVER_TOOLKIT_IMAGE=''
      ARG CUDA_DIST=''

      FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/kernel:latest as kernel

      RUN cat /etc/os-release && dnf repolist

      FROM ${DRIVER_TOOLKIT_IMAGE} as builder

      RUN cat /etc/os-release && dnf repolist

      ARG BASE_URL='https://us.download.nvidia.com/tesla'

      ARG KERNEL_VERSION=''
      ARG RHEL_VERSION=''
      ARG RHEL_VERSION_MAJOR=''

      ARG BUILD_ARCH=''
      ARG TARGET_ARCH=''

      ARG DRIVER_VERSION=''
      ARG DRIVER_EPOCH=''
      ARG DRIVER_OPEN='false'
      ARG DRIVER_PATH='kernel'

      ARG BUILDER_USER=''
      ARG BUILDER_EMAIL=''
      ARG DRIVER_STREAM_TYPE=''

      RUN useradd -u 1001 -m -s /bin/bash builder

      COPY --from=kernel /root/rpmbuild/RPMS/x86_64/kernel-headers-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-devel-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-devel-matched-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-core-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-modules-core-${KERNEL_VERSION}.rpm /tmp/
      RUN dnf config-manager --disable centos-ceph-quincy centos-nfv-openvswitch centos-openstack-zed centos-rabbitmq-38 rhel-10-server-ose rt \
          && dnf install -y /tmp/kernel-*.x86_64.rpm && dnf clean all

      USER builder

      WORKDIR /home/builder
      COPY --chown=1001:0 x509-configuration.ini x509-configuration.ini

      RUN export KVER=$(echo ${KERNEL_VERSION} | cut -d '-' -f 1) \
              KREL=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/\.el.*$//') \
              KDIST=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/^.*\(\.el.\).*$/\1/') \
              DRIVER_STREAM=$(echo ${DRIVER_VERSION} | cut -d '.' -f 1) \
          && if [ "${DRIVER_OPEN}" == "true" ] ; then export DRIVER_PATH="${DRIVER_PATH}-open" ; fi \
          && git clone --depth 1 --single-branch -b rhel${RHEL_VERSION_MAJOR} https://github.com/NVIDIA/yum-packaging-precompiled-kmod \
          && cd yum-packaging-precompiled-kmod \
          && mkdir BUILD BUILDROOT RPMS SRPMS SOURCES SPECS \
          && mkdir nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH} \
          && curl -sLOf ${BASE_URL}/${DRIVER_VERSION}/NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run \
          && sh ./NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run --extract-only --target tmp \
          && if [ "${DRIVER_STREAM_TYPE}" == "development" ] ; then \
              export DRIVER_OPEN='true' ; \
              git clone --depth 1 --single-branch -b ${DRIVER_VERSION} https://github.com/NVIDIA/open-gpu-kernel-modules ; \
              mv open-gpu-kernel-modules/${DRIVER_PATH} nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH}/kernel ; \
          else \
              mv tmp/${DRIVER_PATH} nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH}/kernel ; \
          fi \
          && tar -cJf SOURCES/nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH}.tar.xz nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH} \
          && mv kmod-nvidia.spec SPECS/ \
          && sed -i -e "s/\$USER/${BUILDER_USER}/" -e "s/\$EMAIL/${BUILDER_EMAIL}/" ${HOME}/x509-configuration.ini \
          && openssl req -x509 -new -nodes -utf8 -sha256 -days 36500 -batch \
            -config ${HOME}/x509-configuration.ini \
            -outform DER -out SOURCES/public_key.der \
            -keyout SOURCES/private_key.priv \
          && rpmbuild \
              --define "% _arch ${BUILD_ARCH}" \
              --define "%_topdir $(pwd)" \
              --define "debug_package %{nil}" \
              --define "kernel ${KVER}" \
              --define "kernel_release ${KREL}" \
              --define "kernel_dist ${KDIST}" \
              --define "driver ${DRIVER_VERSION}" \
              --define "epoch ${DRIVER_EPOCH}" \
              --define "driver_branch ${DRIVER_STREAM}" \
              -v -bb SPECS/kmod-nvidia.spec

      FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/cuda:13.0-base-${CUDA_DIST}

      ARG BASE_URL='https://us.download.nvidia.com/tesla'

      ARG KERNEL_VERSION=''
      ARG KERNEL_VERSION_NOARCH=''
      ARG RHEL_VERSION=''

      ARG DRIVER_STREAM_TYPE=''

      ARG DRIVER_TYPE=passthrough
      ENV DRIVER_TYPE=${DRIVER_TYPE}

      ARG DRIVER_VERSION=''
      ENV DRIVER_VERSION=${DRIVER_VERSION}

      ARG CUDA_VERSION=''
      ENV CUDA_VERSION=${CUDA_VERSION}

      ARG BUILD_ARCH=''
      ARG TARGET_ARCH=''
      ENV TARGETARCH=${TARGET_ARCH}

      ENV SMDEV_CONTAINER_OFF=1
      ARG DISABLE_VGPU_VERSION_CHECK=true
      ENV DISABLE_VGPU_VERSION_CHECK=$DISABLE_VGPU_VERSION_CHECK

      USER root

      COPY --chmod=744 nvidia-driver /usr/local/bin
      COPY --chmod=744 common.sh /usr/local/bin
      COPY --from=builder /home/builder/yum-packaging-precompiled-kmod/RPMS/${TARGET_ARCH}/*.rpm /rpms/
      COPY --from=builder --chmod=444 /home/builder/yum-packaging-precompiled-kmod/tmp/firmware/*.bin /opt/lib/firmware/nvidia/${DRIVER_VERSION}/

      RUN rm -rf /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH} \
          && mkdir -p /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/proc \
          && touch /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/modules.order \
          && touch /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/modules.builtin \
          && depmod ${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}

      COPY --from=builder /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/kernel/drivers/gpu/drm/drm.ko.xz /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/kernel/drivers/gpu/drm/drm.ko.xz
      COPY --from=kernel /root/rpmbuild/RPMS/x86_64/kernel-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-modules-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-modules-core-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-core-${KERNEL_VERSION}.rpm /root/rpmbuild/RPMS/x86_64/kernel-modules-core-${KERNEL_VERSION}.rpm /tmp/

      RUN curl -Lo /usr/local/bin/ocp_dtk_entrypoint https://raw.githubusercontent.com/NVIDIA/gpu-driver-container/refs/heads/main/rhel10/ocp_dtk_entrypoint && chmod +x /usr/local/bin/ocp_dtk_entrypoint

      RUN dnf config-manager --disable centos-ceph-quincy centos-nfv-openvswitch centos-openstack-zed centos-rabbitmq-38 rhel-10-server-ose rt \
          && dnf install -y /tmp/kernel-*.rpm /rpms/kmod-nvidia-*.rpm && dnf clean all

      RUN    export DRIVER_STREAM=$(echo ${DRIVER_VERSION} | cut -d '.' -f 1) \
          && if [ "${DRIVER_STREAM_TYPE}" == "development" ] ; then \
              curl -sLOf ${BASE_URL}/${DRIVER_VERSION}/NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run \
              sh ./NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run \
                  --silent \
                  --accept-license \
                  --no-kernel-modules \
                  --no-nvidia-modprobe \
                  --no-rebuild-initramfs \
              && rm NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run ; \
          else \
              CUDA_VERSION_ARRAY=(${CUDA_VERSION//./ }) && CUDA_DASHED_VERSION=${CUDA_VERSION_ARRAY[0]}-${CUDA_VERSION_ARRAY[1]} \
              && echo rm /etc/rhsm-host REMOVED \
              && echo /usr/local/bin/rhsm-register REMOVED \
              && dnf -y module enable nvidia-driver:${DRIVER_STREAM}/default \
              && dnf install -y \
                  nvidia-driver-cuda-${DRIVER_VERSION} \
                  nvidia-driver-libs-${DRIVER_VERSION} \
                  cuda-compat-${CUDA_DASHED_VERSION} \
                  cuda-cudart-${CUDA_DASHED_VERSION} \
                  nvidia-persistenced-${DRIVER_VERSION} \
              && if [ "$DRIVER_TYPE" != "vgpu" ] && [ "$TARGETARCH" != "arm64" ]; then \
                  versionArray=(${DRIVER_VERSION//./ }); \
                  DRIVER_BRANCH=${versionArray[0]}; \
                  dnf module enable -y nvidia-driver:${DRIVER_BRANCH} && \
                  dnf install -y nvidia-fabric-manager-${DRIVER_VERSION} libnvidia-nscq-${DRIVER_BRANCH}-${DRIVER_VERSION} ; \
              fi \
              && dnf clean all; \
          fi

      LABEL io.k8s.display-name="NVIDIA Driver Container"
      LABEL name="NVIDIA Driver Container"
      LABEL vendor="NVIDIA"
      LABEL version="${DRIVER_VERSION}"
      LABEL release="N/A"
      LABEL summary="Provision the NVIDIA driver through containers"
      LABEL description="See summary"

      RUN mkdir /licenses && mv /NGC-DL-CONTAINER-LICENSE /licenses/NGC-DL-CONTAINER-LICENSE
      RUN rm -f /etc/yum.repos.d/cuda.repo
      RUN ls /opt/lib/firmware/nvidia/ && ls /opt/lib/firmware/nvidia/${DRIVER_VERSION}/
      ENTRYPOINT ["nvidia-driver", "init"]
    git:
      uri: 'https://github.com/jggc/gpu-driver-container.git'
    contextDir: /rhel10/precompiled
  triggers:
    - type: ConfigChange
  runPolicy: Serial
---
# MODIFIED: The 'kernel' BuildConfig's Dockerfile is updated below.
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: kernel
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'kernel:latest'
  resources: {}
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      # Use a proper Red Hat UBI 10 base image.
      # FROM registry.access.redhat.com/ubi10/ubi:latest
      #
      # # MODIFIED: Add the CentOS Stream 10 CRB (CodeReady Builder) repository.
      # # This repository is required for the build dependencies of the kernel,
      # # which are fetched by the 'dnf builddep' command in kernel.sh.
      # # The kernel.sh script will then enable this repo using 'dnf config-manager'.
      # RUN dnf config-manager --add-repo https://mirror.stream.centos.org/10-stream/CRB/x86_64/os/

      FROM quay.io/centos/centos:stream10

      # Install the necessary toolchain for building RPMs from source.
      RUN dnf install -y --setopt=install_weak_deps=false \
          dnf-utils \
          findutils \
          gcc \
          git \
          jq \
          make \
          openssl \
          rpm-build \
          tar \
          xz && \
          dnf clean all

      # The rest of the build process remains the same.
      RUN cat /etc/os-release && dnf repolist
      ADD kernel.sh /kernel.sh
      RUN chmod +x /kernel.sh; /kernel.sh
    configMaps:
      - configMap:
          name: kernel
  runPolicy: Serial
