kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cuda
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: driver
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: kernel
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: true
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: driver-toolkit-centos10
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cuda-repo
  namespace: nvidia-gpu-operator
data:
  cuda.repo-x86_64: |
    [cuda]
    name=cuda
    baseurl=https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64
    enabled=1
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA
binaryData: {}
immutable: false
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dummy-egl
  namespace: nvidia-gpu-operator
immutable: false
data:
  dummy-egl.sh: |-
    #!/bin/bash
    set -euo pipefail

    echo "Building and installing dummy egl package to work around this issue : https://github.com/NVIDIA/yum-packaging-nvidia-driver/issues/12"
    echo "[*] Installing required build tools..."
    dnf install -y rpm-build rpmdevtools

    echo "[*] Setting up rpmbuild tree..."
    rpmdev-setuptree

    SPECFILE="$HOME/rpmbuild/SPECS/dummy-egl.spec"

    echo "[*] Writing spec file to $SPECFILE..."
    cat > "$SPECFILE" <<'EOF'
    Name: dummy-egl
    Version: 1
    Release: 1
    Summary: Dummy EGL package for dependency workaround
    License: Public Domain
    BuildArch: x86_64
    Provides: egl-gbm = 9999, egl-wayland = 9999, egl-x11 = 9999
    Provides: egl-gbm(x86-64) = 9999, egl-wayland(x86-64) = 9999, egl-x11(x86-64) = 9999

    %description
    This dummy package exists only to satisfy dependency requirements
    for NVIDIA driver libraries on RHEL/CentOS 10 systems, where
    EGL components have been removed.

    %files
    %defattr(-,root,root,-)
    EOF

    echo "[*] Building dummy EGL RPM..."
    rpmbuild -bb "$SPECFILE"

    RPM_OUT="$HOME/rpmbuild/RPMS/x86_64/dummy-egl-1-1.x86_64.rpm"

    echo "[*] Installing built RPM: $RPM_OUT"
    rpm -ivh "$RPM_OUT"

    echo "[✓] Dummy EGL package installed successfully."
    dnf clean all
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kernel
  namespace: nvidia-gpu-operator
immutable: false
data:
  kernel.sh: |-
    #!/bin/bash
    set -ex

    # Enable CRB repo for build dependencies
    dnf config-manager --set-enabled crb

    mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    cd ~/rpmbuild/SOURCES

    CENTOS_REPO_ID="56169485"
    RPM_BRANCH_NAME="c10s"

    # Get current kernel version
    export KVer="$(uname -r)"
    
    echo "Building kernel packages for version: ${KVer}"

    # Fetch kernel source from GitLab by tag
    kernel_source_commit=$(curl -L "https://gitlab.com/api/v4/projects/${CENTOS_REPO_ID}/repository/tags?search=${KVer%.x86_64}" 2>/dev/null | jq --raw-output -e '.[] | .target')
    echo "Kernel source commit: ${kernel_source_commit}"
    
    # Download and repack kernel source
    curl -L "http://gitlab.com/api/v4/projects/${CENTOS_REPO_ID}/repository/archive.tar.gz?sha=${kernel_source_commit}" 2>/dev/null | tar xzf -
    mv centos* linux-${KVer%.x86_64}
    tar -cf - linux-${KVer%.x86_64}/ | xz -0 -T0 - > linux-${KVer%.x86_64}.tar.xz

    # Fetch kernel spec file from RPM repository
    for p in {1..10}; do
      URL="https://gitlab.com/api/v4/projects/23664863/repository/commits?ref_name=${RPM_BRANCH_NAME}&path=kernel.spec&per_page=50&page=${p}"

      echo "attempt ${p}, fetching url : ${URL}"

      CURL_OUTPUT=$(curl -L "${URL}" 2>/dev/null)

      echo "Got output titles"
      # echo $CURL_OUTPUT | jq -e '.[] | .title'

      KERNEL_TITLE="kernel-${KVer%.x86_64}"

      echo "LOOKING FOR ${KERNEL_TITLE}"

      rpm_source_commit=$(echo "${CURL_OUTPUT}" | jq --raw-output -e '.[] | select(.title=="'${KERNEL_TITLE}'") | .id')

      echo "Got rpm_source_commit : ${rpm_source_commit}"

      if [[ -n "${rpm_source_commit}" ]]; then
        echo "Found rpm source commit, cloning repo at this exact commit"
        git init .
        git remote add origin https://gitlab.com/redhat/centos-stream/rpms/kernel.git
        git fetch --depth 1 origin ${rpm_source_commit}
        git checkout ${rpm_source_commit}
        mv kernel.spec ../SPECS/
        break
      fi
    done

    cd ~/rpmbuild/

    # Install build dependencies
    dnf builddep -y SPECS/kernel.spec

    # Build kernel RPMs
    rpmbuild -bb \
      --with baseonly \
      --without pae \
      --without debug \
      --without zfcpdump \
      --without arm64_64k \
      --without realtime \
      --without realtime_arm64_64k \
      --without cross_headers \
      --without perf \
      --without tools \
      --without debuginfo \
      --with kernel_abi_stablelists \
      --without selftests \
      --clean \
      --target x86_64 \
      SPECS/kernel.spec

    # Cleanup to reduce image size
    rm -rf ~/rpmbuild/BUILD
    rm -rf ~/rpmbuild/BUILDROOT
    rm -rf ~/rpmbuild/SOURCES
    dnf clean all
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: driver-toolkit-centos10
  namespace: nvidia-gpu-operator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'driver-toolkit-centos10:latest'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/centos/centos:stream10'
  source:
    type: Dockerfile
    dockerfile: |
      FROM quay.io/centos/centos:stream10

      # Enable CRB repository
      RUN dnf config-manager --set-enabled crb

      # Install build toolchain
      RUN dnf install -y --setopt=install_weak_deps=false \
          dnf-utils \
          findutils \
          gcc \
          git \
          jq \
          make \
          openssl \
          rpm-build \
          rpmdevtools \
          tar \
          kmod \
          xz \
          elfutils-libelf-devel \
          && dnf clean all
  triggers:
    - type: ConfigChange
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: kernel
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'kernel:latest'
  resources: {}
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'driver-toolkit-centos10:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/driver-toolkit-centos10:latest

      ADD kernel.sh /kernel.sh
      RUN chmod +x /kernel.sh && /kernel.sh
    configMaps:
      - configMap:
          name: kernel
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cuda
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'cuda:13.0-base-centos10'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'driver-toolkit-centos10:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |
      FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/driver-toolkit-centos10:latest

      ENV PKG_CMD=dnf
      ENV NVARCH=x86_64
      ENV NVIDIA_REQUIRE_CUDA="cuda>=13.0 brand=unknown,driver>=580,driver<581"

      COPY cuda.repo-x86_64 /etc/yum.repos.d/cuda.repo

      LABEL maintainer="NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>"

      RUN NVIDIA_GPGKEY_SUM=afbea87d3b979b3788ef34223aeeb323ade481128e2c133723ae99b8a51368bb && \
          curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/rhel10/${NVARCH}/CDF6BA43.pub | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA && \
          echo "$NVIDIA_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA" | sha256sum -c --strict -

      ENV CUDA_VERSION=13.0.2

      RUN ${PKG_CMD} install -y \
          cuda-cudart-13-0 \
          cuda-compat-13-0 \
          && ${PKG_CMD} clean all \
          && rm -rf /var/cache/yum/*

      RUN echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/nvidia.conf

      ENV PATH=/usr/local/cuda/bin:${PATH}
      ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64

      ADD https://gitlab.com/nvidia/container-images/cuda/-/raw/master/NGC-DL-CONTAINER-LICENSE /NGC-DL-CONTAINER-LICENSE

      ENV NVIDIA_VISIBLE_DEVICES=all
      ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
    configMaps:
      - configMap:
          name: cuda-repo
        destinationDir: .
  triggers:
    - type: ConfigChange
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: driver-pb
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'driver:580-6.12.0-142.el10.x86_64-centos10'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: DRIVER_TOOLKIT_IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/driver-toolkit-centos10:latest'
        - name: CUDA_DIST
          value: centos10
        - name: KERNEL_VERSION
          value: 6.12.0-142.el10.x86_64
        - name: KERNEL_VERSION_NOARCH
          value: 6.12.0-142.el10
        - name: RHEL_VERSION_MAJOR
          value: '10'
        - name: BUILD_ARCH
          value: x86_64
        - name: TARGET_ARCH
          value: x86_64
        - name: DRIVER_VERSION
          value: 580.105.08
        - name: DRIVER_EPOCH
          value: '1'
        - name: BUILDER_USER
          value: Jean-Gabriel Gill-Couture
        - name: BUILDER_EMAIL
          value: jg@nationtech.io
        - name: CUDA_VERSION
          value: 13.0.2
  postCommit: {}
  source:
    type: Git
    dockerfile: |
      ARG DRIVER_TOOLKIT_IMAGE=''
      ARG CUDA_DIST=''

      # Stage 1: Get pre-built kernel packages
      FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/kernel:latest as kernel

      # Stage 2: Build NVIDIA kernel modules
      FROM ${DRIVER_TOOLKIT_IMAGE} as builder

      ARG BASE_URL='https://us.download.nvidia.com/tesla'
      ARG KERNEL_VERSION=''
      ARG RHEL_VERSION_MAJOR=''
      ARG BUILD_ARCH=''
      ARG TARGET_ARCH=''
      ARG DRIVER_VERSION=''
      ARG DRIVER_EPOCH=''
      ARG BUILDER_USER=''
      ARG BUILDER_EMAIL=''

      # Create builder user and setup RPM build environment first
      RUN useradd -u 1001 -m -s /bin/bash builder

      USER builder
      WORKDIR /home/builder

      # Setup RPM build environment
      RUN rpmdev-setuptree

      # Switch back to root for package installation
      USER root

      # Install kernel packages from kernel build stage
      COPY --from=kernel /root/rpmbuild/RPMS/x86_64/kernel-headers-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-devel-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-devel-matched-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-core-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-modules-core-${KERNEL_VERSION}.rpm \
                         /tmp/

      RUN dnf install -y /tmp/kernel-*.rpm && dnf clean all

      # Verify kernel-devel installation
      RUN ls -la /usr/src/kernels/${KERNEL_VERSION}/ && \
          test -f /usr/src/kernels/${KERNEL_VERSION}/scripts/module.lds || \
          test -f /usr/src/kernels/${KERNEL_VERSION}/scripts/module-common.lds

      # Switch back to builder user
      USER builder
      WORKDIR /home/builder

      # Copy x509 configuration for module signing
      COPY --chown=1001:0 x509-configuration.ini x509-configuration.ini

      # Extract kernel version components
      RUN export KVER=$(echo ${KERNEL_VERSION} | cut -d '-' -f 1) && \
          export KREL=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/\.el.*$//') && \
          export KDIST=$(echo ${KERNEL_VERSION} | sed -E 's/.*(\.el[0-9]+).*/\1/') && \
          export DRIVER_STREAM=$(echo ${DRIVER_VERSION} | cut -d '.' -f 1) && \
          echo "KVER=${KVER}" > /tmp/kver.env && \
          echo "KREL=${KREL}" >> /tmp/kver.env && \
          echo "KDIST=${KDIST}" >> /tmp/kver.env && \
          echo "DRIVER_STREAM=${DRIVER_STREAM}" >> /tmp/kver.env

      # Clone precompiled kmod packaging repo
      RUN git clone --depth 1 --single-branch -b rhel${RHEL_VERSION_MAJOR} \
          https://github.com/jggc/yum-packaging-precompiled-kmod

      WORKDIR /home/builder/yum-packaging-precompiled-kmod

      # Download and extract NVIDIA driver
      RUN . /tmp/kver.env && \
          curl -sLOf ${BASE_URL}/${DRIVER_VERSION}/NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run && \
          sh ./NVIDIA-Linux-${TARGET_ARCH}-${DRIVER_VERSION}.run --extract-only --target tmp && \
          mkdir -p nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH} && \
          mv tmp/kernel nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH}/ && \
          tar -cJf ~/rpmbuild/SOURCES/nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH}.tar.xz nvidia-kmod-${DRIVER_VERSION}-${BUILD_ARCH}

      # Move spec file and generate signing keys
      RUN mv kmod-nvidia.spec ~/rpmbuild/SPECS/ && \
          sed -i -e "s/\$USER/${BUILDER_USER}/" -e "s/\$EMAIL/${BUILDER_EMAIL}/" ${HOME}/x509-configuration.ini && \
          openssl req -x509 -new -nodes -utf8 -sha256 -days 36500 -batch \
            -config ${HOME}/x509-configuration.ini \
            -outform DER -out ~/rpmbuild/SOURCES/public_key.der \
            -keyout ~/rpmbuild/SOURCES/private_key.priv

      # Build kernel module RPMs using kernel-devel from installed package
      RUN . /tmp/kver.env && \
          rpmbuild \
            --define "_arch ${BUILD_ARCH}" \
            --define "debug_package %{nil}" \
            --define "kernel ${KVER}" \
            --define "kernel_release ${KREL}" \
            --define "kernel_dist ${KDIST}" \
            --define "driver ${DRIVER_VERSION}" \
            --define "epoch ${DRIVER_EPOCH}" \
            --define "driver_branch ${DRIVER_STREAM}" \
            -v -bb ~/rpmbuild/SPECS/kmod-nvidia.spec

      # Stage 3: Final runtime image
      FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/cuda:13.0-base-${CUDA_DIST}

      ARG BASE_URL='https://us.download.nvidia.com/tesla'
      ARG KERNEL_VERSION=''
      ARG KERNEL_VERSION_NOARCH=''
      ARG DRIVER_VERSION=''
      ARG CUDA_VERSION=''
      ARG BUILD_ARCH=''
      ARG TARGET_ARCH=''

      ARG DRIVER_TYPE=passthrough
      ENV DRIVER_TYPE=${DRIVER_TYPE}
      ENV DRIVER_VERSION=${DRIVER_VERSION}
      ENV CUDA_VERSION=${CUDA_VERSION}
      ENV TARGETARCH=${TARGET_ARCH}
      ENV SMDEV_CONTAINER_OFF=1

      ARG DISABLE_VGPU_VERSION_CHECK=true
      ENV DISABLE_VGPU_VERSION_CHECK=$DISABLE_VGPU_VERSION_CHECK

      USER root

      # Install dummy EGL package to workaround RHEL10 missing EGL libraries
      ADD dummy-egl.sh /root/dummy-egl.sh
      RUN chmod +x /root/dummy-egl.sh && /root/dummy-egl.sh

      RUN dnf install kmod -y && dnf clean all

      # Copy driver scripts
      COPY --chmod=744 nvidia-driver /usr/local/bin
      COPY --chmod=744 common.sh /usr/local/bin

      # Copy built kernel module RPMs
      COPY --from=builder /home/builder/rpmbuild/RPMS/${TARGET_ARCH}/*.rpm /rpms/

      # Copy firmware files
      COPY --from=builder --chmod=444 /home/builder/yum-packaging-precompiled-kmod/tmp/firmware/*.bin /opt/lib/firmware/nvidia/${DRIVER_VERSION}/

      # Setup minimal module directory structure for depmod
      RUN rm -rf /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH} && \
          mkdir -p /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/proc && \
          touch /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/modules.order && \
          touch /lib/modules/${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}/modules.builtin && \
          depmod ${KERNEL_VERSION_NOARCH}.${BUILD_ARCH}

      # Copy kernel packages (needed for depmod and module loading)
      COPY --from=kernel /root/rpmbuild/RPMS/x86_64/kernel-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-modules-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-modules-core-${KERNEL_VERSION}.rpm \
                         /root/rpmbuild/RPMS/x86_64/kernel-core-${KERNEL_VERSION}.rpm \
                         /tmp/

      # Copy OCP DTK entrypoint
      RUN curl -Lo /usr/local/bin/ocp_dtk_entrypoint \
          https://raw.githubusercontent.com/jggc/gpu-driver-container/refs/heads/main/rhel10/ocp_dtk_entrypoint && \
          chmod +x /usr/local/bin/ocp_dtk_entrypoint

      # Install NVIDIA driver components
      RUN export DRIVER_STREAM=$(echo ${DRIVER_VERSION} | cut -d '.' -f 1) && \
          CUDA_VERSION_ARRAY=(${CUDA_VERSION//./ }) && \
          CUDA_DASHED_VERSION=${CUDA_VERSION_ARRAY[0]}-${CUDA_VERSION_ARRAY[1]} && \
          echo "INFO: Installing precompiled kernel modules and driver components" && \
          dnf install -y \
            /rpms/kmod-nvidia-*.rpm \
            mesa-libEGL \
            mesa-libgbm \
            libwayland-egl \
            egl-utils \
            nvidia-driver-cuda-${DRIVER_VERSION} \
            nvidia-driver-libs-${DRIVER_VERSION} \
            nvidia-persistenced-${DRIVER_VERSION} && \
          if [ "$DRIVER_TYPE" != "vgpu" ] && [ "$TARGETARCH" != "arm64" ]; then \
            echo "INFO: Installing Fabric Manager components" && \
            dnf install -y \
              nvidia-fabricmanager-${DRIVER_VERSION} \
              libnvidia-nscq-${DRIVER_VERSION} || true; \
          fi && \
          dnf clean all

      # Labels
      LABEL io.k8s.display-name="NVIDIA Driver Container"
      LABEL name="NVIDIA Driver Container"
      LABEL vendor="NVIDIA"
      LABEL version="${DRIVER_VERSION}"
      LABEL release="N/A"
      LABEL summary="Provision the NVIDIA driver through containers"
      LABEL description="See summary"

      # Licensing
      RUN mkdir -p /licenses && mv /NGC-DL-CONTAINER-LICENSE /licenses/NGC-DL-CONTAINER-LICENSE

      # Cleanup
      RUN rm -f /etc/yum.repos.d/cuda.repo

      ENTRYPOINT ["nvidia-driver", "init"]
    configMaps:
      - configMap:
          name: dummy-egl
    git:
      uri: 'https://github.com/jggc/gpu-driver-container.git'
    contextDir: /rhel10/precompiled
  triggers:
    - type: ConfigChange
  runPolicy: Serial
