# kind: ImageStream
# apiVersion: image.openshift.io/v1
# metadata:
#   name: cuda
#   namespace: nvidia-gpu-operator
# spec:
#   lookupPolicy:
#     local: false
# ---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: driver
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
# kind: ImageStream
# apiVersion: image.openshift.io/v1
# metadata:
#   name: kernel
#   namespace: nvidia-gpu-operator
# spec:
#   lookupPolicy:
#     local: true
# ---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: driver-toolkit-centos10
  namespace: nvidia-gpu-operator
spec:
  lookupPolicy:
    local: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cuda-repo
  namespace: nvidia-gpu-operator
data:
  cuda.repo-x86_64: |
    [cuda]
    name=cuda
    baseurl=https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64
    enabled=1
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA
binaryData: {}
immutable: false
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dummy-egl
  namespace: nvidia-gpu-operator
immutable: false
data:
  dummy-egl.sh: |-
    #!/bin/bash
    set -euo pipefail

    echo "Building and installing dummy egl package to work around this issue : https://github.com/NVIDIA/yum-packaging-nvidia-driver/issues/12"
    echo "[*] Installing required build tools..."
    dnf install -y rpm-build rpmdevtools

    echo "[*] Setting up rpmbuild tree..."
    rpmdev-setuptree

    SPECFILE="$HOME/rpmbuild/SPECS/dummy-egl.spec"

    echo "[*] Writing spec file to $SPECFILE..."
    cat > "$SPECFILE" <<'EOF'
    Name: dummy-egl
    Version: 1
    Release: 1
    Summary: Dummy EGL package for dependency workaround
    License: Public Domain
    BuildArch: x86_64
    Provides: egl-gbm = 9999, egl-wayland = 9999, egl-x11 = 9999
    Provides: egl-gbm(x86-64) = 9999, egl-wayland(x86-64) = 9999, egl-x11(x86-64) = 9999

    %description
    This dummy package exists only to satisfy dependency requirements
    for NVIDIA driver libraries on RHEL/CentOS 10 systems, where
    EGL components have been removed.

    %files
    %defattr(-,root,root,-)
    EOF

    echo "[*] Building dummy EGL RPM..."
    rpmbuild -bb "$SPECFILE"

    RPM_OUT="$HOME/rpmbuild/RPMS/x86_64/dummy-egl-1-1.x86_64.rpm"

    echo "[*] Installing built RPM: $RPM_OUT"
    rpm -ivh "$RPM_OUT"

    echo "[✓] Dummy EGL package installed successfully."
    dnf clean all
---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: kernel
#   namespace: nvidia-gpu-operator
# immutable: false
# data:
#   kernel.sh: |-
#     #!/bin/bash
#     set -ex
#
#     # Enable CRB repo for build dependencies
#     dnf config-manager --set-enabled crb
#
#     mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
#     cd ~/rpmbuild/SOURCES
#
#     CENTOS_REPO_ID="56169485"
#     RPM_BRANCH_NAME="c10s"
#
#     # Get current kernel version
#     export KVer="$(uname -r)"
#
#     echo "Building kernel packages for version: ${KVer}"
#
#     # Fetch kernel source from GitLab by tag
#     kernel_source_commit=$(curl -L "https://gitlab.com/api/v4/projects/${CENTOS_REPO_ID}/repository/tags?search=${KVer%.x86_64}" 2>/dev/null | jq --raw-output -e '.[] | .target')
#     echo "Kernel source commit: ${kernel_source_commit}"
#
#     # Download and repack kernel source
#     curl -L "http://gitlab.com/api/v4/projects/${CENTOS_REPO_ID}/repository/archive.tar.gz?sha=${kernel_source_commit}" 2>/dev/null | tar xzf -
#     mv centos* linux-${KVer%.x86_64}
#     tar -cf - linux-${KVer%.x86_64}/ | xz -0 -T0 - > linux-${KVer%.x86_64}.tar.xz
#
#     # Fetch kernel spec file from RPM repository
#     for p in {1..10}; do
#       URL="https://gitlab.com/api/v4/projects/23664863/repository/commits?ref_name=${RPM_BRANCH_NAME}&path=kernel.spec&per_page=50&page=${p}"
#
#       echo "attempt ${p}, fetching url : ${URL}"
#
#       CURL_OUTPUT=$(curl -L "${URL}" 2>/dev/null)
#
#       echo "Got output titles"
#       # echo $CURL_OUTPUT | jq -e '.[] | .title'
#
#       KERNEL_TITLE="kernel-${KVer%.x86_64}"
#
#       echo "LOOKING FOR ${KERNEL_TITLE}"
#
#       rpm_source_commit=$(echo "${CURL_OUTPUT}" | jq --raw-output -e '.[] | select(.title=="'${KERNEL_TITLE}'") | .id')
#
#       echo "Got rpm_source_commit : ${rpm_source_commit}"
#
#       if [[ -n "${rpm_source_commit}" ]]; then
#         echo "Found rpm source commit, cloning repo at this exact commit"
#         git init .
#         git remote add origin https://gitlab.com/redhat/centos-stream/rpms/kernel.git
#         git fetch --depth 1 origin ${rpm_source_commit}
#         git checkout ${rpm_source_commit}
#         mv kernel.spec ../SPECS/
#         break
#       fi
#     done
#
#     cd ~/rpmbuild/
#
#     # Install build dependencies
#     dnf builddep -y SPECS/kernel.spec
#
#     # Build kernel RPMs
#     rpmbuild -bb \
#       --with baseonly \
#       --without pae \
#       --without debug \
#       --without zfcpdump \
#       --without arm64_64k \
#       --without realtime \
#       --without realtime_arm64_64k \
#       --without cross_headers \
#       --without perf \
#       --without tools \
#       --without debuginfo \
#       --with kernel_abi_stablelists \
#       --without selftests \
#       --clean \
#       --target x86_64 \
#       SPECS/kernel.spec
#
#     # Cleanup to reduce image size
#     rm -rf ~/rpmbuild/BUILD
#     rm -rf ~/rpmbuild/BUILDROOT
#     rm -rf ~/rpmbuild/SOURCES
#     dnf clean all
# ---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: driver-toolkit-centos10
  namespace: nvidia-gpu-operator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'driver-toolkit-centos10:latest'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/centos/centos:stream10'
      buildArgs:
        - name: "KERNEL_VERSION_NOARCH" # Get it with `uname -r | sed "s/\.$(uname -p)//"`
          value: "6.12.0-142.el10"
        - name: "GCC_VERSION" # Extract from `cat /proc/version` and verify with dnf list gcc --showduplicates to get the exact right value
          value: "14.3.1-2.1.el10"
  source:
    type: Dockerfile
    dockerfile: |
      FROM quay.io/centos/centos:stream10

      ARG KERNEL_VERSION_NOARCH=''
      ARG GCC_VERSION=''

      # Enable CRB repository
      RUN dnf config-manager --set-enabled crb \
        && dnf install -y epel-release \
        && dnf config-manager --set-enabled epel \
        # Install build toolchain
        && dnf install -y --setopt=install_weak_deps=false \
          gcc-${GCC_VERSION} \
          git \
          jq \
          make \
          dkms \
          openssl \
          tar \
          xz \
          elfutils-libelf-devel \
          kmod \
          kernel-headers-${KERNEL_VERSION_NOARCH} \
          kernel-devel-${KERNEL_VERSION_NOARCH}  \
          kernel-devel-matched-${KERNEL_VERSION_NOARCH}  \
        && dnf clean all
  triggers:
    - type: ConfigChange
  runPolicy: Serial
---
# kind: BuildConfig
# apiVersion: build.openshift.io/v1
# metadata:
#   name: kernel
#   namespace: nvidia-gpu-operator
# spec:
#   nodeSelector: null
#   output:
#     to:
#       kind: ImageStreamTag
#       name: 'kernel:latest'
#   resources: {}
#   successfulBuildsHistoryLimit: 1
#   failedBuildsHistoryLimit: 1
#   strategy:
#     type: Docker
#     dockerStrategy:
#       from:
#         kind: ImageStreamTag
#         name: 'driver-toolkit-centos10:latest'
#   postCommit: {}
#   source:
#     type: Dockerfile
#     dockerfile: |-
#       FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/driver-toolkit-centos10:latest
#
#       ADD kernel.sh /kernel.sh
#       RUN chmod +x /kernel.sh && /kernel.sh
#     configMaps:
#       - configMap:
#           name: kernel
#   triggers:
#     - type: ConfigChange
#     - type: ImageChange
#   runPolicy: Serial
---
# kind: BuildConfig
# apiVersion: build.openshift.io/v1
# metadata:
#   name: cuda
#   namespace: nvidia-gpu-operator
# spec:
#   nodeSelector: null
#   output:
#     to:
#       kind: ImageStreamTag
#       name: 'cuda:13.0-base-centos10'
#   resources: {}
#   successfulBuildsHistoryLimit: 2
#   failedBuildsHistoryLimit: 2
#   strategy:
#     type: Docker
#     dockerStrategy:
#       from:
#         kind: ImageStreamTag
#         name: 'driver-toolkit-centos10:latest'
#   postCommit: {}
#   source:
#     type: Dockerfile
#     dockerfile: |
#       FROM image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/driver-toolkit-centos10:latest
#
#       ENV PKG_CMD=dnf
#       ENV NVARCH=x86_64
#       ENV NVIDIA_REQUIRE_CUDA="cuda>=13.0 brand=unknown,driver>=580,driver<581"
#
#       COPY cuda.repo-x86_64 /etc/yum.repos.d/cuda.repo
#
#       LABEL maintainer="NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>"
#
#       RUN NVIDIA_GPGKEY_SUM=afbea87d3b979b3788ef34223aeeb323ade481128e2c133723ae99b8a51368bb && \
#           curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/rhel10/${NVARCH}/CDF6BA43.pub | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA && \
#           echo "$NVIDIA_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA" | sha256sum -c --strict -
#
#       ENV CUDA_VERSION=13.0.2
#
#       RUN ${PKG_CMD} install -y \
#           cuda-cudart-13-0 \
#           cuda-compat-13-0 \
#           && ${PKG_CMD} clean all \
#           && rm -rf /var/cache/yum/*
#
#       RUN echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/nvidia.conf
#
#       ENV PATH=/usr/local/cuda/bin:${PATH}
#       ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64
#
#       ADD https://gitlab.com/nvidia/container-images/cuda/-/raw/master/NGC-DL-CONTAINER-LICENSE /NGC-DL-CONTAINER-LICENSE
#
#       ENV NVIDIA_VISIBLE_DEVICES=all
#       ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
#     configMaps:
#       - configMap:
#           name: cuda-repo
#         destinationDir: .
#   triggers:
#     - type: ConfigChange
#   runPolicy: Serial
# ---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: driver-pb
  namespace: nvidia-gpu-operator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'driver:580-6.12.0-142.el10.x86_64-centos10'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: DRIVER_TOOLKIT_IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/nvidia-gpu-operator/driver-toolkit-centos10:latest'
        - name: "CUDA_DIST"
          value: "centos10"
        - name: "KERNEL_VERSION"
          value: "6.12.0-142.el10.x86_64"
        - name: "KERNEL_VERSION_NOARCH"
          value: "6.12.0-142.el10"
        - name: "RHEL_VERSION_MAJOR"
          value: '10'
        - name: "BUILD_ARCH"
          value: "x86_64"
        - name: "TARGET_ARCH"
          value: "x86_64"
        - name: "NVARCH"
          value: "x86_64"
        - name: "DRIVER_VERSION"
          value: "580.105.08"
        - name: "DRIVER_EPOCH"
          value: '1'
        - name: "BUILDER_USER"
          value: "Jean-Gabriel Gill-Couture"
        - name: "BUILDER_EMAIL"
          value: "jg@nationtech.io"
        - name: "CUDA_VERSION"
          value: "13.0.2"
  postCommit: {}
  source:
    type: Git
    dockerfile: |
      ARG DRIVER_TOOLKIT_IMAGE=''
      
      # Stage 1: Build kernel modules with DKMS
      FROM ${DRIVER_TOOLKIT_IMAGE} as builder

      ARG KERNEL_VERSION=''
      ARG DRIVER_VERSION=''
      ARG NVARCH=''
      
      # Add NVIDIA CUDA repository
      COPY cuda.repo-x86_64 /etc/yum.repos.d/cuda.repo

      RUN NVIDIA_GPGKEY_SUM=afbea87d3b979b3788ef34223aeeb323ade481128e2c133723ae99b8a51368bb && \
        curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/rhel10/${NVARCH}/CDF6BA43.pub | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA && \
        echo "$NVIDIA_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA" | sha256sum -c --strict -

      # Install NVIDIA driver with DKMS to build modules
      RUN dnf install -y \
          nvidia-driver-cuda-${DRIVER_VERSION} \
          kmod-nvidia-open-dkms-${DRIVER_VERSION} \
          && dnf clean all

      # DKMS will automatically build the modules for the installed kernel
      # Modules will be in /lib/modules/${KERNEL_VERSION}/extra/
      RUN ls -la /lib/modules/${KERNEL_VERSION}/extra/ && \
          modinfo /lib/modules/${KERNEL_VERSION}/extra/nvidia.ko.xz

      # Stage 2: Final runtime image
      FROM 'quay.io/centos/centos:stream10'

      ARG KERNEL_VERSION=''
      ARG DRIVER_VERSION=''
      ARG CUDA_VERSION=''
      ARG TARGETARCH=''

      ENV DRIVER_VERSION=${DRIVER_VERSION}
      ENV CUDA_VERSION=${CUDA_VERSION}
      ENV KERNEL_VERSION=${KERNEL_VERSION}
      ENV TARGETARCH=${TARGETARCH}
      ARG DRIVER_TYPE=passthrough
      ENV DRIVER_TYPE=${DRIVER_TYPE}

      # Add NVIDIA CUDA repository
      COPY --from=builder /etc/yum.repos.d/cuda.repo /etc/yum.repos.d/
      COPY --from=builder /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA

      # Install runtime driver libraries (no kernel modules, no DKMS)
      RUN dnf install -y epel-release \
          && dnf config-manager --set-enabled epel \
          && dnf install -y \
          nvidia-driver-cuda-${DRIVER_VERSION} \
          nvidia-driver-libs-${DRIVER_VERSION} \
          nvidia-persistenced-${DRIVER_VERSION} \
          nvidia-fabricmanager-${DRIVER_VERSION} \
          libnvidia-nscq-${DRIVER_VERSION} \
          mesa-libEGL \
          mesa-libgbm \
          libwayland-egl \
          util-linux \
          && dnf clean all 

      # Copy pre-built kernel modules from builder stage
      # [root@nvidia-driver-daemonset-6 extra]# ls
      # drivers  nvidia-drm.ko.xz  nvidia-modeset.ko.xz  nvidia-peermem.ko.xz  nvidia-uvm.ko.xz  nvidia.ko.xz
      # [root@nvidia-driver-daemonset-6 extra]# pwd
      # /usr/lib/modules/6.12.0-142.el10.x86_64/extra
      COPY --from=builder /lib/modules/${KERNEL_VERSION}/extra/ /lib/modules/${KERNEL_VERSION}/extra/
      RUN depmod

      # Copy firmware files, they should al
      # COPY --from=builder /usr/lib/firmware/nvidia/${DRIVER_VERSION}/ /opt/lib/firmware/nvidia/${DRIVER_VERSION}/

      # Copy driver scripts from upstream
      COPY --chmod=744 nvidia-driver /usr/local/bin/
      COPY --chmod=744 common.sh /usr/local/bin/

      # Copy OCP DTK entrypoint
      RUN curl -Lo /usr/local/bin/ocp_dtk_entrypoint \
          https://raw.githubusercontent.com/jggc/gpu-driver-container/refs/heads/main/rhel10/ocp_dtk_entrypoint && \
          chmod +x /usr/local/bin/ocp_dtk_entrypoint

      # Labels
      LABEL io.k8s.display-name="NVIDIA Driver Container"
      LABEL name="NVIDIA Driver Container"
      LABEL vendor="NVIDIA"
      LABEL version="${DRIVER_VERSION}"
      LABEL summary="Provision the NVIDIA driver through containers"
      LABEL description="Precompiled NVIDIA kernel modules for ${KERNEL_VERSION}"

      # Licensing
      RUN mkdir -p /licenses
      ADD https://gitlab.com/nvidia/container-images/cuda/-/raw/master/NGC-DL-CONTAINER-LICENSE /licenses/NGC-DL-CONTAINER-LICENSE


      ENTRYPOINT ["nvidia-driver", "init"]
    configMaps:
      - configMap:
          name: dummy-egl
      - configMap:
          name: cuda-repo
          destinationDir: .
    git:
      uri: 'https://github.com/jggc/gpu-driver-container.git'
    contextDir: /rhel10/precompiled
  triggers:
    - type: ConfigChange
  runPolicy: Serial
